import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/header/Navbar"; // adjust path
import { AuthProvider } from "../context/AuthContext";
import PostNotification from "../components/notification/PostNotification";
import { SocketProvider } from "../providers/SocketProviders";
import { ToastContainer } from "react-toastify";
// import 'react-toastify/dist/ReactToastify.css';
import { ReactQueryProvider } from "../lib/QueryClientProvider";
import { OnlineUsersProvider } from "../context/OnlineUserContex";
import { UnreadProvider } from "../context/UnreadContex";
import NetworkBanner from "@/components/ui/NetworkBanner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#2563eb" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ReactQueryProvider>
            <SocketProvider>
              <UnreadProvider>
                <OnlineUsersProvider>
                  <NetworkBanner />
                  <Navbar />
                  <PostNotification />
                  <ToastContainer newestOnTop />
                  {children}
                </OnlineUsersProvider>
              </UnreadProvider>
            </SocketProvider>
          </ReactQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
